name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          render-manifest: render.yaml
          render-api-key: ${{ secrets.MY_RENDER_API_KEY }}
          render-service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
